# Generated by Django 5.1.15 on 2026-06-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("percent_off", models.PositiveSmallIntegerField(default=0)),
                ("free_days", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("max_redemptions", models.PositiveIntegerField(default=0)),
                ("times_redeemed", models.PositiveIntegerField(default=0)),
                ("stripe_coupon_id", models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name="subscription",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="tier",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
