# Generated by Django 5.1.15 on 2026-06-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_board_theme_user_premium_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_used_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="premium_tier",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
