# Generated by Django 5.1.15 on 2026-06-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_has_used_trial_user_premium_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]
