# Generated by Django 5.1.15 on 2026-06-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_opt_in",
            field=models.BooleanField(default=True),
        ),
    ]
