# Generated by Django 5.1.15 on 2026-06-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_more_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="translation_group",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
