# Generated by Django 5.1.15 on 2026-06-06 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Esperando rival"),
                            ("active", "En juego"),
                            ("finished", "Terminada"),
                            ("aborted", "Abortada"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("rated", models.BooleanField(default=True)),
                ("max_players", models.PositiveSmallIntegerField(default=2)),
                ("board", models.JSONField(blank=True, default=dict)),
                ("bag", models.JSONField(blank=True, default=list)),
                ("turn_index", models.PositiveSmallIntegerField(default=0)),
                ("consecutive_passes", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("play", "Jugada"),
                            ("pass", "Paso"),
                            ("exchange", "Cambio"),
                            ("resign", "Abandono"),
                        ],
                        default="play",
                        max_length=10,
                    ),
                ),
                ("placements", models.JSONField(blank=True, default=list)),
                ("words", models.JSONField(blank=True, default=list)),
                ("points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat", models.PositiveSmallIntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("rack", models.JSONField(blank=True, default=list)),
                ("result", models.CharField(blank=True, max_length=4)),
                ("rating_before", models.IntegerField(blank=True, null=True)),
                ("rating_after", models.IntegerField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["seat"],
                "unique_together": {("game", "player"), ("game", "seat")},
            },
        ),
    ]
