# Generated by Django 5.1.15 on 2026-06-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="language",
            field=models.CharField(
                choices=[("es", "Español"), ("en", "English")],
                default="es",
                max_length=5,
            ),
        ),
    ]
