# Generated by Django 5.1.15 on 2026-06-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="clock_increment",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="clock_initial",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="turn_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="time_left_ms",
            field=models.IntegerField(default=0),
        ),
    ]
