# Generated by Django 5.1.15 on 2026-06-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_game_draw_offer_by_game_next_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="ai_level",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
